apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  defaultBackend:
    service:
      name: k8s-training-service
      port:
        number: 3000
#  rules:
#    - http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: k8s-training-service
#                port:
#                  number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-training-service
spec:
  selector:
    app: web
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-training-web
  labels:
    app: web
spec:
  replicas: 1
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: k8s-basic-training_web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      restartPolicy: Always
  selector:
    matchLabels:
      app: web
